# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_gcc_earlier:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: g++ -o main sample/main.cpp -std=c++11
      - run: ./main
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: g++ -o main sample/main.cpp -std=c++14
      - run: ./main
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: g++ -o main sample/main.cpp -std=c++20
      - run: ./main

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_earlier
      - build_gcc_6
      - build_gcc_latest
    
